export const authActionTypes = {
  LOGIN_REQUEST: "LOGIN_REQUEST",
  LOGOUT_REQUEST: "LOGOUT_REQUEST",
};

export const visitorActionTypes = {
  FETCH_VISITORS_REQUEST: "visitor/FETCH_VISITORS_REQUEST",
  FETCH_VISITOR_BY_ID_REQUEST: "visitor/FETCH_VISITOR_BY_ID_REQUEST",
  CHECKIN_VISITOR_REQUEST: "visitor/CHECKIN_VISITOR_REQUEST",
  CHECKOUT_VISITOR_REQUEST: "visitor/CHECKOUT_VISITOR_REQUEST",
  FETCH_STATS_REQUEST: "FETCH_STATS_REQUEST",
};
