export const authActionTypes = {
  LOGIN_REQUEST: "LOGIN_REQUEST",
  LOGOUT_REQUEST: "LOGOUT_REQUEST",
};

export const visitorActionTypes = {
  FETCH_VISITORS_REQUEST: "visitor/FETCH_VISITORS_REQUEST",
  FETCH_VISITOR_BY_ID_REQUEST: "visitor/FETCH_VISITOR_BY_ID_REQUEST",
  CHECKIN_VISITOR_REQUEST: "visitor/CHECKIN_VISITOR_REQUEST",
  CHECKOUT_VISITOR_REQUEST: "visitor/CHECKOUT_VISITOR_REQUEST",
  FETCH_STATS_REQUEST: "FETCH_STATS_REQUEST",
};

export const visitorRequestActionTypes = {
  FETCH_REQUESTS_REQUEST: "requests/FETCH_REQUESTS_REQUEST",
  FETCH_PENDING_REQUESTS_REQUEST: "requests/FETCH_PENDING_REQUESTS_REQUEST",
  CREATE_PRE_APPROVAL_REQUEST: "requests/CREATE_PRE_APPROVAL_REQUEST",
  APPROVE_REQUEST_REQUEST: "requests/APPROVE_REQUEST_REQUEST",
  REJECT_REQUEST_REQUEST: "requests/REJECT_REQUEST_REQUEST",
} as const;
